# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import fileupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=fileupload.models.generate_random_uploaded_filename, verbose_name='Uploaded file'),
        ),
    ]
